In [1]:
import numpy as np

In [2]:
vertices=[
    (1.5, -1, -1), (1.5, 1, -1), (-1.5, 1, -1), (-1.5, -1, -1),
    (-1.5, -1, 1), (1.5, -1, 1), (1.5, 1, 1), (-1.5 ,1 ,1)
    ]

#La lista de las caras con el indice de los vertices que las conforman
caras = [
    (0, 1, 2, 3), #Cara trasera
    (3, 4, 5, 0), #Cara inferior
    (0, 1, 6, 5), #cara derecha
    (6, 1, 2, 7), #Cara superior
    (4, 7, 2, 3), #Cara izquierda
    (5, 6, 7, 4) #Cara delantera
]


#Lista de las normales
normales = [
    (0.0, 0.0, -1.0), #Cara trasera
    (0.0, -1.0, 0.0), #Cara inferior
    (1.0, 0.0, 0.0), #Cara derecha
    (0.0, 1.0, 0.0), #Cara superior
    (-1.0, 0.0, 0.0), #Cara izquierda
    (0.0, 0.0, 1.0)  #Cara delantera
]

#Vertices de texturas
vertices_textura = [
    (0.0, 0.0),
    (-1.0, 0.0),
    (-1.0, 1.0),
    (0.0, 1.0),
]

In [3]:
cuarto = []

In [4]:
for i,cara in enumerate(caras[:-1]):
    for j,index in enumerate(cara):
        cuarto.extend(vertices_textura[j])
        cuarto.extend(normales[i])
        cuarto.extend(vertices[index])        

In [5]:
cuarto = np.array(cuarto,dtype="f4")
cuarto

array([ 0. ,  0. ,  0. ,  0. , -1. ,  1.5, -1. , -1. , -1. ,  0. ,  0. ,
        0. , -1. ,  1.5,  1. , -1. , -1. ,  1. ,  0. ,  0. , -1. , -1.5,
        1. , -1. ,  0. ,  1. ,  0. ,  0. , -1. , -1.5, -1. , -1. ,  0. ,
        0. ,  0. , -1. ,  0. , -1.5, -1. , -1. , -1. ,  0. ,  0. , -1. ,
        0. , -1.5, -1. ,  1. , -1. ,  1. ,  0. , -1. ,  0. ,  1.5, -1. ,
        1. ,  0. ,  1. ,  0. , -1. ,  0. ,  1.5, -1. , -1. ,  0. ,  0. ,
        1. ,  0. ,  0. ,  1.5, -1. , -1. , -1. ,  0. ,  1. ,  0. ,  0. ,
        1.5,  1. , -1. , -1. ,  1. ,  1. ,  0. ,  0. ,  1.5,  1. ,  1. ,
        0. ,  1. ,  1. ,  0. ,  0. ,  1.5, -1. ,  1. ,  0. ,  0. ,  0. ,
        1. ,  0. ,  1.5,  1. ,  1. , -1. ,  0. ,  0. ,  1. ,  0. ,  1.5,
        1. , -1. , -1. ,  1. ,  0. ,  1. ,  0. , -1.5,  1. , -1. ,  0. ,
        1. ,  0. ,  1. ,  0. , -1.5,  1. ,  1. ,  0. ,  0. , -1. ,  0. ,
        0. , -1.5, -1. ,  1. , -1. ,  0. , -1. ,  0. ,  0. , -1.5,  1. ,
        1. , -1. ,  1. , -1. ,  0. ,  0. , -1.5,  1

In [6]:
cuarto.shape

(160,)

In [7]:
!mkdir modelos_propios

Ya existe el subdirectorio o el archivo modelos_propios.


In [8]:
np.save("./modelos_propios/cuarto",cuarto)

### DIO chiquito

In [98]:
cara = [
        (0.75, 0, 0.5), (0.75,1.0,0.5),
        (0, 1.0, 0.5), (0, 0, 0.5)
    ]
texCoords = [
       (1.0, 1.0), (0.0, 1.0),
       (0.0, 0.0), (1.0, 0.0)
]

In [99]:
orden = [0,1,2,3]

In [100]:
normal = (0.0, 0.0, 1.0)

In [101]:
DIO_chiquito = []

In [102]:
for i in orden:
        DIO_chiquito.extend(texCoords[i][::-1])
        DIO_chiquito.extend(normal)
        DIO_chiquito.extend(cara[i])
        

In [103]:
DIO_chiquito = np.array(DIO_chiquito, dtype="f4")

In [104]:
DIO_chiquito.shape

(32,)

In [105]:
DIO_chiquito.reshape(4,8)

array([[1.  , 1.  , 0.  , 0.  , 1.  , 0.75, 0.  , 0.5 ],
       [1.  , 0.  , 0.  , 0.  , 1.  , 0.75, 1.  , 0.5 ],
       [0.  , 0.  , 0.  , 0.  , 1.  , 0.  , 1.  , 0.5 ],
       [0.  , 1.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.5 ]], dtype=float32)

In [106]:
np.save("./modelos_propios/DIO_chiquito",DIO_chiquito)

In [107]:
np.load("./modelos_propios/DIO_chiquito.npy")

array([1.  , 1.  , 0.  , 0.  , 1.  , 0.75, 0.  , 0.5 , 1.  , 0.  , 0.  ,
       0.  , 1.  , 0.75, 1.  , 0.5 , 0.  , 0.  , 0.  , 0.  , 1.  , 0.  ,
       1.  , 0.5 , 0.  , 1.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.5 ],
      dtype=float32)

In [18]:
konoDio = []

In [19]:
for j,index in enumerate(caras[-1]):
    konoDio.extend(vertices_textura[j])
    konoDio.extend(normales[i])
    konoDio.extend(vertices[index])

In [20]:
konoDio = np.array(konoDio)
konoDio.shape

(32,)

In [21]:
konoDio.reshape(4,8)

array([[ 0. ,  0. ,  0. ,  0. , -1. ,  1.5, -1. ,  1. ],
       [-1. ,  0. ,  0. ,  0. , -1. ,  1.5,  1. ,  1. ],
       [-1. ,  1. ,  0. ,  0. , -1. , -1.5,  1. ,  1. ],
       [ 0. ,  1. ,  0. ,  0. , -1. , -1.5, -1. ,  1. ]])

In [22]:
np.save("./modelos_propios/konoDioDa",konoDio)